"""Export normalised OSRS drop groups into a Python data module."""

from argparse import ArgumentParser
from pathlib import Path
from pprint import pformat

from utils.osrs_drop_database_excel import load_drop_database_xlsx


GENERATED_HEADER = """\"\"\"Generated OSRS drop group data.

Do not edit this file manually. Regenerate it from the maintained drop
database workbook.
\"\"\""""


def build_drop_group_data_records(database):
    return tuple(
        {
            "drop_group_id": group.group_id,
            "display_name": group.group_name,
            "source_ids": group.source_ids,
            "source_names": group.source_names,
            "drop_ids": group.drop_ids,
            "drop_names": group.drop_names,
            "drop_rates": group.drop_rates,
            "drop_counting_modes": group.drop_counting_modes,
            "drop_quantities": group.drop_quantities,
            "access_notes": group.access_notes,
            "notes": group.notes,
            "include_pet": group.include_pet,
        }
        for group in sorted(
            database.groups,
            key=lambda group: group.group_id,
        )
    )


def format_drop_group_data_module(database):
    records = build_drop_group_data_records(
        database
    )

    return (
        GENERATED_HEADER
        + "\n\n"
        + "DROP_GROUP_DATA = "
        + pformat(
            records,
            sort_dicts=False,
            width=88,
        )
        + "\n"
    )


def write_drop_group_data_module(database, output_path):
    output_path = Path(
        output_path
    )

    output_path.write_text(
        format_drop_group_data_module(
            database
        ),
        encoding="utf-8",
    )

    return output_path


def build_argument_parser():
    parser = ArgumentParser(
        description="Export OSRS drop group data from the drop database workbook.",
    )
    parser.add_argument(
        "workbook_path",
        help="Path to the maintained drop database .xlsx file.",
    )
    parser.add_argument(
        "--sheet-name",
        default=None,
        help="Optional worksheet name. Defaults to the first worksheet.",
    )
    parser.add_argument(
        "--output",
        default="utils/osrs_drop_group_data.py",
        help="Output Python data module path.",
    )

    return parser


def main(argv=None):
    parser = build_argument_parser()
    args = parser.parse_args(
        argv
    )

    database = load_drop_database_xlsx(
        args.workbook_path,
        sheet_name=args.sheet_name,
    )
    output_path = write_drop_group_data_module(
        database,
        args.output,
    )

    print(
        f"Wrote {len(database.groups)} drop groups to {output_path}"
    )


if __name__ == "__main__":
    main()
